version: "3.4"

# For descriptions of the various services defined here, see the `platform` README.

services:
  queue-watcher:
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ${REGISTRY_SLASH}queue-watcher${COLON_TAG}
      context: ./queue-watcher
    image: ${REGISTRY_SLASH}queue-watcher${COLON_TAG}
