apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        task: '${TASK}'
      labels:
        app: demo-pipeline
    spec:
      restartPolicy: Never
      containers:
      - name: cruncher-pipeline
        image: nixery.dev/shell/iputils/jq
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          set -euo pipefail
          echo "TASK: ${TASK}"
          # Note: we use single quotes here; the TASK variable is expanded by envsubst and already contains double quotes
          duration=$(echo '${TASK}' | jq -r .duration)
          target=$(echo '${TASK}' | jq -r .target)
          timeout=$(( duration + 30 ))
          echo "Pinging ${target} for ${duration} seconds!"
          ping -w "${duration}" "${target}"
          echo "All done!"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
